name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - format_project

jobs:
  build_gRPC_project:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: eWaterCycle/setup-grpc@v5
      with:
        grpc-version: 1.51.1

    - name: Build
      run: |
          mkdir build && cd build
          cmake .. && make

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          gRPC_CPP_CMake/bin/*
          gRPC_CPP_CMake/lib/*

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: binaries
        path: binaries/
